# Generated by Django 4.2.6 on 2023-10-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Stock Keeping Unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default=0),
        ),
    ]
